fold unit tests into main workflow

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -49,7 +49,6 @@ jobs:
         id: restore-cache
         with:
           path: .rattler-build/artifacts/  # this path is gitignored, so it won't be in the checkout, only the cache
-          # todo: use the same cache key to also skip no-deps build in subsequent job if cache hit
           key: ${{ runner.os }}-${{ needs.set-deps-hash.outputs.deps-hash }}
       - name: Install rattler-build & build artifacts (i.e. local conda channel)
         if: steps.restore-cache.outputs.cache-hit != 'true'
@@ -68,6 +67,69 @@ jobs:
             !.rattler-build/artifacts/src_cache
           if-no-files-found: error
           compression-level: 0
+
+  unit-test:
+    runs-on: ubuntu-latest
+    needs:
+      - build-conda-channel
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: [
+          "3.10",
+          "3.11",
+          "3.12",
+        ]
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Download conda channel
+        uses: actions/download-artifact@v4
+        with:
+          name: rattler-artifacts
+          path: tmp/conda-channel
+      - name: Log conda channel contents
+        run: ls -lR tmp/conda-channel
+      - name: Setup Micromamba
+        uses: mamba-org/setup-micromamba@v1
+        with:
+          cache-environment: true  # todo how to handle caching in this case?
+          cache-downloads: true
+          init-shell: bash
+      - name: Install all dependencies with conda
+        shell: bash -leo pipefail {0}
+        run: |  # todo: ecoscope-workflows build variants (e.g. "compile-only" w/out ecoscope-core-tasks, etc.)
+          micromamba install python=${{ matrix.python-version }} -c conda-forge --yes \
+          micromamba install ecoscope-workflows \
+          -c file://$(pwd)/tmp/conda-channel \
+          -c conda-forge \
+          --only-deps \
+          --yes
+
+      - name: Install our package from current head ref
+        shell: bash -leo pipefail {0}
+        run: |
+          python -m pip install . --no-deps
+
+      - name: Run doctests
+        shell: bash -leo pipefail {0}
+        run: |
+          python -m pytest -v ecoscope_workflows/ --doctest-modules \
+          --ignore=ecoscope_workflows/visualize.py
+
+      - name: Export shell name and conda env name to env
+        run: |
+          echo 'SHELL="bash -leo pipefail"' >> $GITHUB_ENV
+          echo "CONDA_ENV_NAME=${{ matrix.environment-name }}" >> $GITHUB_ENV
+
+      - name: Test with pytest
+        env:
+          EARTHRANGER_SERVER: ${{ secrets.EARTHRANGER_SERVER }}
+          EARTHRANGER_USERNAME: ${{ secrets.EARTHRANGER_USERNAME }}
+          EARTHRANGER_PASSWORD: ${{ secrets.EARTHRANGER_PASSWORD }}
+        shell: bash -leo pipefail {0}
+        run: |  # FIXME: run IO tests separately since they require credentials which could expire and fail the tests
+          python -m pytest -m "not io" tests -vvv
 
   build-only-deps:
     runs-on: ubuntu-latest
