mamba exe again

diff --git a/.github/workflows/unit-test.yaml b/.github/workflows/unit-test.yaml
--- a/.github/workflows/unit-test.yaml
+++ b/.github/workflows/unit-test.yaml
@@ -39,8 +39,10 @@ jobs:
           python -m pytest -v ecoscope_workflows/ --doctest-modules \
           --ignore=ecoscope_workflows/visualize.py
 
-      - name: Export shell name to env
-        run: echo 'SHELL="bash -leo pipefail"' >> $GITHUB_ENV
+      - name: Export shell name and conda env name to env
+        run: |
+          echo 'SHELL="bash -leo pipefail"' >> $GITHUB_ENV
+          echo "CONDA_ENV_NAME=${{ matrix.environment-name }}" >> $GITHUB_ENV
 
       - name: Test with pytest
         env:
